/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

#include "stm32f407xx.h"


int main(void)
{
    /* Loop forever */
	GPIO_Handle_t gpioLEDDHandler={0};
	gpioLEDDHandler=(GPIO_Handle_t){
			.pGPIOx=GPIOD,
			.GPIO_PinConfig=(GPIO_PinConfig_t){
				.GPIO_PinNumber=GPIO_PIN_NUM_14,
				.GPIO_PinMode=GPIO_MODE_OUTPUT,
				.GPIO_PinOutputType=GPIO_OUTPUT_TYPE_PP,
			}
	};

	GPIO_Handle_t gpioButtonDHandler={0};
	gpioButtonDHandler=(GPIO_Handle_t){
			.pGPIOx=GPIOA,
			.GPIO_PinConfig=(GPIO_PinConfig_t){
				.GPIO_PinNumber=GPIO_PIN_NUM_0,
				.GPIO_PinMode=GPIO_MODE_IT_RT,
				.GPIO_PinPullUpPullDownMode=GPIO_NO_PULL_DONW_AND_UP,
			}
	};

	GPIO_Init(&gpioLEDDHandler);
	GPIO_Init(&gpioButtonDHandler);

	GPIO_IRQPriorityConfig(IRQ_NUM_EXTI0, 1);
	GPIO_IRQInterruptConfig(IRQ_NUM_EXTI0, GPIO_IRQ_ENABLE);


	while(1);
}

void EXTI0_IRQHandler(void)
{
	GPIO_IRQHandling(GPIO_PIN_NUM_0);
	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NUM_14);
}
